kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: datree-policy-check  
  image: hadarco/test
  settings:
    token:
      from_secret: datree_token
    path: "exampleFile.yaml"
    cliArguments: -s 1.22.0
    isHelmChart: false
    helmArguments:
    isKustomization: false
    kustomizeArguments:

  when:
    event:
    - push
    - pull_request

