kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: datree-policy-check  
  image: hadarco/test
  settings:
    token:
      from_secret: datree_token
    path: "kustomize"
    cliArguments: -s 1.23.0
    isHelmChart: false
    helmArguments:
    isKustomization: true
    kustomizeArguments:

  when:
    event:
    - push
    - pull_request


