kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: datree-policy-check  
  image: datree/datree
  settings:
    token:
      from_secret: datree_token
    path: exampleFile.yaml
    cliArguments: -s 1.24.0
    isHelmChart: false

  when:
    event:
    - push
    - pull_request
