kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: datree-policy-check  
  image: datree/drone-datree
  settings:
    token:
      from_secret: datree_token
    path: "exampleFile.yaml"

  when:
    event:
    - push
    - pull_request

