kind: pipeline
name: default

steps:
- name: datree-policy-check  
  image: datree/datree
  settings:
    token:
      from_secret: datree_token
    path:
    cliArguments: -s 1.24.0
    isHelmChart: false
    helmArguments: 
  when:
    event:
    - push
    - pull_request
